const ITINERARIES=[
{id:"jfk-can-cz328",title:"JFK→CAN Nonstop",routeFamily:"Direct CAN",paymentType:"cash",recommendation:"Strong",recommendationReason:"Nonstop CAN $1,520/pp",outboundDate:"2026-07-28",returnDate:"2026-08-30",origin:"JFK",destination:"CAN",returnOrigin:"CAN",returnDestination:"JFK",airline:"China Southern",alliance:"SkyTeam",cashPricePerPerson:1520,totalCashForFamily:6080,adjustedTotalForFamily:6080,pointsProgram:null,pointsPerPerson:null,totalPointsForFamily:null,taxesPerPerson:0,cpp:null,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:950,totalDurationMinutesReturn:960,stopsOutbound:0,stopsReturn:0,sameTicket:true,baggageIncluded:"2x23kg",changePolicy:"$200 fee",cancellationPolicy:"Non-refundable",awardSeatsAvailable:null,familyBookable:true,riskLevel:"Low",riskChips:[],
outboundSegments:[{segmentNumber:1,marketingAirline:"CZ",flightNumber:"CZ600",aircraft:"A380",cabin:"Economy",origin:"JFK",destination:"CAN",departureTime:"01:45",arrivalTime:"05:35+1",durationMinutes:950,layoverAfterMinutes:0,bookingClass:"L"}],
returnSegments:[{segmentNumber:1,marketingAirline:"CZ",flightNumber:"CZ399",aircraft:"A380",cabin:"Economy",origin:"CAN",destination:"JFK",departureTime:"20:00",arrivalTime:"22:00",durationMinutes:960,layoverAfterMinutes:0,bookingClass:"L"}],
links:{googleFlights:"https://www.google.com/travel/flights?q=JFK+to+CAN+July+28",airlineDirect:"https://www.csair.com/us/en/",united:null,chase:null},notes:"Best nonstop option. Summer peak pricing.",lastCheckedAt:"2026-05-09",dataSource:"Google Flights"},

{id:"ewr-can-tk-ist",title:"EWR→IST→CAN via Turkish",routeFamily:"One-stop CAN",paymentType:"cash",recommendation:"Strong",recommendationReason:"CAN 1-stop $1,190/pp, 26h",outboundDate:"2026-07-29",returnDate:"2026-09-01",origin:"EWR",destination:"CAN",returnOrigin:"CAN",returnDestination:"EWR",airline:"Turkish Airlines",alliance:"Star Alliance",cashPricePerPerson:1190,totalCashForFamily:4760,adjustedTotalForFamily:4760,pointsProgram:null,pointsPerPerson:null,totalPointsForFamily:null,taxesPerPerson:0,cpp:null,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:1560,totalDurationMinutesReturn:1500,stopsOutbound:1,stopsReturn:1,sameTicket:true,baggageIncluded:"2x23kg",changePolicy:"$150 fee",cancellationPolicy:"Non-refundable",awardSeatsAvailable:null,familyBookable:true,riskLevel:"Low",riskChips:["Long duration"],
outboundSegments:[
{segmentNumber:1,marketingAirline:"TK",flightNumber:"TK30",aircraft:"777-300ER",cabin:"Economy",origin:"EWR",destination:"IST",departureTime:"22:30",arrivalTime:"16:30+1",durationMinutes:630,layoverAfterMinutes:195,bookingClass:"T"},
{segmentNumber:2,marketingAirline:"TK",flightNumber:"TK72",aircraft:"A330",cabin:"Economy",origin:"IST",destination:"CAN",departureTime:"19:45",arrivalTime:"11:00+1",durationMinutes:600,layoverAfterMinutes:0,bookingClass:"T"}],
returnSegments:[
{segmentNumber:1,marketingAirline:"TK",flightNumber:"TK73",aircraft:"A330",cabin:"Economy",origin:"CAN",destination:"IST",departureTime:"12:30",arrivalTime:"19:00",durationMinutes:720,layoverAfterMinutes:150,bookingClass:"T"},
{segmentNumber:2,marketingAirline:"TK",flightNumber:"TK29",aircraft:"777-300ER",cabin:"Economy",origin:"IST",destination:"EWR",departureTime:"21:30",arrivalTime:"01:30+1",durationMinutes:630,layoverAfterMinutes:0,bookingClass:"T"}],
links:{googleFlights:"https://www.google.com/travel/flights?q=EWR+to+CAN+July+29",airlineDirect:"https://www.turkishairlines.com/"},notes:"Affordable but long. IST layover is comfortable.",lastCheckedAt:"2026-05-09",dataSource:"Google Flights"},

{id:"jfk-hkg-cx-nonstop",title:"JFK→HKG Nonstop Cathay",routeFamily:"HKG Alternative",paymentType:"cash",recommendation:"Strong",recommendationReason:"HKG saves $320 vs CAN adjusted",outboundDate:"2026-07-28",returnDate:"2026-08-30",origin:"JFK",destination:"HKG",returnOrigin:"HKG",returnDestination:"JFK",airline:"Cathay Pacific",alliance:"Oneworld",cashPricePerPerson:1150,totalCashForFamily:4600,adjustedTotalForFamily:5400,pointsProgram:null,pointsPerPerson:null,totalPointsForFamily:null,taxesPerPerson:0,cpp:null,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:960,totalDurationMinutesReturn:975,stopsOutbound:0,stopsReturn:0,sameTicket:true,baggageIncluded:"1x30kg",changePolicy:"$250 fee",cancellationPolicy:"Non-refundable",awardSeatsAvailable:null,familyBookable:true,riskLevel:"Low",riskChips:["Airport transfer"],
outboundSegments:[{segmentNumber:1,marketingAirline:"CX",flightNumber:"CX845",aircraft:"A350-1000",cabin:"Economy",origin:"JFK",destination:"HKG",departureTime:"00:30",arrivalTime:"05:30+1",durationMinutes:960,layoverAfterMinutes:0,bookingClass:"N"}],
returnSegments:[{segmentNumber:1,marketingAirline:"CX",flightNumber:"CX846",aircraft:"A350-1000",cabin:"Economy",origin:"HKG",destination:"JFK",departureTime:"18:00",arrivalTime:"21:15",durationMinutes:975,layoverAfterMinutes:0,bookingClass:"N"}],
links:{googleFlights:"https://www.google.com/travel/flights?q=JFK+to+HKG+July+28",airlineDirect:"https://www.cathaypacific.com/cx/en_US.html",cathayAsiaMiles:"https://www.cathaypacific.com/cx/en_US/redeem-miles/flights.html"},notes:"Nonstop HKG, then high-speed rail to GZ (~1h). Cathay A350 is very comfortable.",lastCheckedAt:"2026-05-09",dataSource:"Google Flights"},

{id:"ewr-hkg-br-tpe",title:"EWR→TPE→HKG via EVA Air",routeFamily:"HKG Alternative",paymentType:"cash",recommendation:"Watch",recommendationReason:"HKG 1-stop, decent price",outboundDate:"2026-07-30",returnDate:"2026-09-02",origin:"EWR",destination:"HKG",returnOrigin:"HKG",returnDestination:"EWR",airline:"EVA Air",alliance:"Star Alliance",cashPricePerPerson:1080,totalCashForFamily:4320,adjustedTotalForFamily:5120,pointsProgram:null,pointsPerPerson:null,totalPointsForFamily:null,taxesPerPerson:0,cpp:null,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:1200,totalDurationMinutesReturn:1230,stopsOutbound:1,stopsReturn:1,sameTicket:true,baggageIncluded:"2x23kg",changePolicy:"$150 fee",cancellationPolicy:"Non-refundable",awardSeatsAvailable:null,familyBookable:true,riskLevel:"Low",riskChips:["Airport transfer"],
outboundSegments:[
{segmentNumber:1,marketingAirline:"BR",flightNumber:"BR31",aircraft:"777-300ER",cabin:"Economy",origin:"EWR",destination:"TPE",departureTime:"00:05",arrivalTime:"05:45+1",durationMinutes:900,layoverAfterMinutes:135,bookingClass:"K"},
{segmentNumber:2,marketingAirline:"BR",flightNumber:"BR857",aircraft:"A321",cabin:"Economy",origin:"TPE",destination:"HKG",departureTime:"08:00",arrivalTime:"09:55",durationMinutes:115,layoverAfterMinutes:0,bookingClass:"K"}],
returnSegments:[
{segmentNumber:1,marketingAirline:"BR",flightNumber:"BR856",aircraft:"A321",cabin:"Economy",origin:"HKG",destination:"TPE",departureTime:"11:00",arrivalTime:"12:50",durationMinutes:110,layoverAfterMinutes:190,bookingClass:"K"},
{segmentNumber:2,marketingAirline:"BR",flightNumber:"BR32",aircraft:"777-300ER",cabin:"Economy",origin:"TPE",destination:"EWR",departureTime:"16:00",arrivalTime:"19:30",durationMinutes:930,layoverAfterMinutes:0,bookingClass:"K"}],
links:{googleFlights:"https://www.google.com/travel/flights?q=EWR+to+HKG+July+30",airlineDirect:"https://www.evaair.com/"},notes:"Via TPE. Good connection, EVA is family-friendly airline.",lastCheckedAt:"2026-05-09",dataSource:"Google Flights"},

{id:"jfk-pvg-mu-nonstop",title:"JFK→PVG Nonstop China Eastern",routeFamily:"PVG/SHA Alternative",paymentType:"cash",recommendation:"Watch",recommendationReason:"PVG saves < $400 adjusted",outboundDate:"2026-07-28",returnDate:"2026-08-31",origin:"JFK",destination:"PVG",returnOrigin:"PVG",returnDestination:"JFK",airline:"China Eastern",alliance:"SkyTeam",cashPricePerPerson:950,totalCashForFamily:3800,adjustedTotalForFamily:5400,pointsProgram:null,pointsPerPerson:null,totalPointsForFamily:null,taxesPerPerson:0,cpp:null,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:900,totalDurationMinutesReturn:930,stopsOutbound:0,stopsReturn:0,sameTicket:true,baggageIncluded:"2x23kg",changePolicy:"$200 fee",cancellationPolicy:"Non-refundable",awardSeatsAvailable:null,familyBookable:true,riskLevel:"Medium",riskChips:["Domestic add-on","Airport transfer"],
outboundSegments:[{segmentNumber:1,marketingAirline:"MU",flightNumber:"MU588",aircraft:"777-300ER",cabin:"Economy",origin:"JFK",destination:"PVG",departureTime:"16:00",arrivalTime:"19:00+1",durationMinutes:900,layoverAfterMinutes:0,bookingClass:"M"}],
returnSegments:[{segmentNumber:1,marketingAirline:"MU",flightNumber:"MU587",aircraft:"777-300ER",cabin:"Economy",origin:"PVG",destination:"JFK",departureTime:"11:00",arrivalTime:"12:30",durationMinutes:930,layoverAfterMinutes:0,bookingClass:"M"}],
links:{googleFlights:"https://www.google.com/travel/flights?q=JFK+to+PVG+July+28",airlineDirect:"https://us.ceair.com/"},notes:"Cheap but need domestic flight/train CAN→PVG. Add ~$100-200 + 2.5h.",lastCheckedAt:"2026-05-09",dataSource:"Google Flights"},

{id:"openjaw-jfk-can-hkg-jfk",title:"Open-jaw: JFK→CAN, HKG→JFK",routeFamily:"Open-jaw",paymentType:"cash",recommendation:"Strong",recommendationReason:"Fly into CAN, return from HKG",outboundDate:"2026-07-28",returnDate:"2026-09-01",origin:"JFK",destination:"CAN",returnOrigin:"HKG",returnDestination:"JFK",airline:"CZ + CX",alliance:"Mixed",cashPricePerPerson:1350,totalCashForFamily:5400,adjustedTotalForFamily:5400,pointsProgram:null,pointsPerPerson:null,totalPointsForFamily:null,taxesPerPerson:0,cpp:null,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:950,totalDurationMinutesReturn:975,stopsOutbound:0,stopsReturn:0,sameTicket:false,baggageIncluded:"Varies",changePolicy:"Per airline",cancellationPolicy:"Per airline",awardSeatsAvailable:null,familyBookable:true,riskLevel:"Medium",riskChips:["Separate tickets"],
outboundSegments:[{segmentNumber:1,marketingAirline:"CZ",flightNumber:"CZ600",aircraft:"A380",cabin:"Economy",origin:"JFK",destination:"CAN",departureTime:"01:45",arrivalTime:"05:35+1",durationMinutes:950,layoverAfterMinutes:0,bookingClass:"L"}],
returnSegments:[{segmentNumber:1,marketingAirline:"CX",flightNumber:"CX846",aircraft:"A350-1000",cabin:"Economy",origin:"HKG",destination:"JFK",departureTime:"18:00",arrivalTime:"21:15",durationMinutes:975,layoverAfterMinutes:0,bookingClass:"N"}],
links:{googleFlights:"https://www.google.com/travel/flights",airlineDirect:null},notes:"Best of both: arrive CAN directly, return via HKG. Need separate bookings.",lastCheckedAt:"2026-05-09",dataSource:"Manual"},

{id:"ewr-hkg-ua-award",title:"EWR→HKG United Award",routeFamily:"HKG Alternative",paymentType:"points",recommendation:"Strong",recommendationReason:"1.8 cpp, 4 seats available",outboundDate:"2026-07-28",returnDate:"2026-08-30",origin:"EWR",destination:"HKG",returnOrigin:"HKG",returnDestination:"EWR",airline:"United",alliance:"Star Alliance",cashPricePerPerson:null,totalCashForFamily:null,adjustedTotalForFamily:null,pointsProgram:"United MileagePlus",pointsPerPerson:55000,totalPointsForFamily:220000,taxesPerPerson:85,cpp:1.8,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:960,totalDurationMinutesReturn:1005,stopsOutbound:0,stopsReturn:0,sameTicket:true,baggageIncluded:"2x23kg",changePolicy:"Free for members",cancellationPolicy:"Redeposit miles",awardSeatsAvailable:4,familyBookable:true,riskLevel:"Low",riskChips:[],
outboundSegments:[{segmentNumber:1,marketingAirline:"UA",flightNumber:"UA179",aircraft:"777-200ER",cabin:"Economy",origin:"EWR",destination:"HKG",departureTime:"00:35",arrivalTime:"05:35+1",durationMinutes:960,layoverAfterMinutes:0,bookingClass:"X"}],
returnSegments:[{segmentNumber:1,marketingAirline:"UA",flightNumber:"UA180",aircraft:"777-200ER",cabin:"Economy",origin:"HKG",destination:"EWR",departureTime:"10:00",arrivalTime:"13:45",durationMinutes:1005,layoverAfterMinutes:0,bookingClass:"X"}],
links:{googleFlights:"https://www.google.com/travel/flights?q=EWR+to+HKG",airlineDirect:null,united:"https://www.united.com/en/us/fsr/choose-flights?f=EWR&t=HKG",chase:"https://ultimaterewardspoints.chase.com/travel"},notes:"Saver award, all 4 seats available. Excellent cpp. Transfer from Chase UR or use existing United miles.",lastCheckedAt:"2026-05-09",dataSource:"United.com"},

{id:"ewr-can-ac-yvr-award",title:"EWR→YVR→CAN Aeroplan Award",routeFamily:"One-stop CAN",paymentType:"points",recommendation:"Watch",recommendationReason:"2.2 cpp, 4 seats, but 24h duration",outboundDate:"2026-07-30",returnDate:"2026-08-31",origin:"EWR",destination:"CAN",returnOrigin:"CAN",returnDestination:"EWR",airline:"Air Canada",alliance:"Star Alliance",cashPricePerPerson:null,totalCashForFamily:null,adjustedTotalForFamily:null,pointsProgram:"Chase UR → Aeroplan",pointsPerPerson:50000,totalPointsForFamily:200000,taxesPerPerson:110,cpp:2.2,passengerCount:4,adults:2,children:2,totalDurationMinutesOutbound:1440,totalDurationMinutesReturn:1380,stopsOutbound:1,stopsReturn:1,sameTicket:true,baggageIncluded:"2x23kg",changePolicy:"Free",cancellationPolicy:"Redeposit free",awardSeatsAvailable:4,familyBookable:true,riskLevel:"Low",riskChips:["Long duration"],
outboundSegments:[
{segmentNumber:1,marketingAirline:"AC",flightNumber:"AC735",aircraft:"737 MAX 8",cabin:"Economy",origin:"EWR",destination:"YVR",departureTime:"08:00",arrivalTime:"10:45",durationMinutes:345,layoverAfterMinutes:195,bookingClass:"I"},
{segmentNumber:2,marketingAirline:"AC",flightNumber:"AC025",aircraft:"787-9",cabin:"Economy",origin:"YVR",destination:"CAN",departureTime:"14:00",arrivalTime:"18:00+1",durationMinutes:720,layoverAfterMinutes:0,bookingClass:"I"}],
returnSegments:[
{segmentNumber:1,marketingAirline:"AC",flightNumber:"AC026",aircraft:"787-9",cabin:"Economy",origin:"CAN",destination:"YVR",departureTime:"20:00",arrivalTime:"17:00",durationMinutes:660,layoverAfterMinutes:180,bookingClass:"I"},
{segmentNumber:2,marketingAirline:"AC",flightNumber:"AC736",aircraft:"737 MAX 8",cabin:"Economy",origin:"YVR",destination:"EWR",departureTime:"20:00",arrivalTime:"04:00+1",durationMinutes:300,layoverAfterMinutes:0,bookingClass:"I"}],
links:{aeroplan:"https://www.aircanada.com/aeroplan",chase:"https://ultimaterewardspoints.chase.com/travel"},notes:"Via YVR. Long but family bookable with 4 Aeroplan seats. Transfer Chase UR.",lastCheckedAt:"2026-05-09",dataSource:"Aeroplan"}
];

function getLayoverQuality(mins){
  if(!mins||mins===0)return null;
  if(mins<75)return{label:"Tight",cls:"avoid",icon:"⚠️"};
  if(mins<=120)return{label:"Acceptable",cls:"watch",icon:"⏱️"};
  if(mins<=240)return{label:"Good",cls:"buy",icon:"✅"};
  if(mins<=360)return{label:"Long",cls:"watch",icon:"⏳"};
  if(mins<=720)return{label:"Very Long",cls:"avoid",icon:"😴"};
  return{label:"Overnight",cls:"avoid",icon:"🌙"};
}
function fmtDur(m){const h=Math.floor(m/60);const mm=m%60;return h+"h"+(mm>0?mm+"m":"");}
function fmtTime(t){return t||"—";}
